package model;
// Generated 24/10/2017 08:37:48 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbCadastroGeral generated by hbm2java
 */
@Entity
@Table(name="tb_cadastro_geral"
    ,catalog="bd_cadastro_sesc"
)
public class TbCadastroGeral  implements java.io.Serializable {


     private Integer idtCpf;
     private String nme;
     private String senha;
     private Set<TbPreCadastro> tbPreCadastros = new HashSet<TbPreCadastro>(0);

    public TbCadastroGeral() {
    }

	
    public TbCadastroGeral(String nme, String senha) {
        this.nme = nme;
        this.senha = senha;
    }
    public TbCadastroGeral(String nme, String senha, Set<TbPreCadastro> tbPreCadastros) {
       this.nme = nme;
       this.senha = senha;
       this.tbPreCadastros = tbPreCadastros;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idt_cpf", unique=true, nullable=false)
    public Integer getIdtCpf() {
        return this.idtCpf;
    }
    
    public void setIdtCpf(Integer idtCpf) {
        this.idtCpf = idtCpf;
    }

    
    @Column(name="nme", nullable=false, length=100)
    public String getNme() {
        return this.nme;
    }
    
    public void setNme(String nme) {
        this.nme = nme;
    }

    
    @Column(name="senha", nullable=false, length=20)
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbCadastroGeral")
    public Set<TbPreCadastro> getTbPreCadastros() {
        return this.tbPreCadastros;
    }
    
    public void setTbPreCadastros(Set<TbPreCadastro> tbPreCadastros) {
        this.tbPreCadastros = tbPreCadastros;
    }




}


